# Generated by Django 3.2.7 on 2021-10-25 22:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('authors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inbox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inbox_type', models.CharField(default='', max_length=100)),
                ('inbox_author', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('post_id', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='id')),
                ('post_type', models.CharField(default='', max_length=100, verbose_name='type')),
                ('title', models.CharField(default='', max_length=100)),
                ('source', models.URLField(default='')),
                ('origin', models.URLField(default='')),
                ('description', models.TextField(default='')),
                ('image_content', models.FileField(upload_to='')),
                ('text_content', models.CharField(blank=True, default='', max_length=500, null=True)),
                ('comments', models.URLField()),
                ('published', models.DateTimeField(auto_now_add=True)),
                ('unlisted', models.BooleanField(default=False)),
                ('contentType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('items', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='authors.inbox')),
                ('post_author', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.URLField(default='', verbose_name='@context')),
                ('summary', models.CharField(default='', max_length=100)),
                ('type', models.CharField(default='', max_length=100)),
                ('object', models.URLField()),
                ('like_author', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='author')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('comment_id', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='id')),
                ('comment_type', models.CharField(default='', max_length=100, verbose_name='type')),
                ('comment', models.TextField(default='')),
                ('published', models.DateTimeField(auto_now_add=True)),
                ('comment_author', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('comment_post', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='authors.post')),
                ('contentType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
        ),
    ]
