
# Generated by Django 3.2.7 on 2021-11-26 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inbox',
            name='inbox_type',
            field=models.CharField(default='inbox', max_length=100),
        ),
    ]
