# Generated by Django 3.1.6 on 2021-12-05 22:20

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='followers',
            name='id',
            field=models.CharField(blank=True, default=uuid.uuid4, max_length=1000, primary_key=True, serialize=False, verbose_name='followers_id'),
        ),
    ]
