# Generated by Django 3.1.6 on 2021-12-04 23:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='id',
            field=models.CharField(blank=True, default='post', max_length=100, verbose_name='URL_id'),
        ),
        migrations.AddField(
            model_name='post',
            name='id',
            field=models.CharField(blank=True, default='post', max_length=100, verbose_name='URL_id'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='comment_author',
            field=models.ForeignKey(default='', editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='authors', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='comment',
            name='comment_post',
            field=models.ForeignKey(default='', editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='commentsSrc', to='authors.post'),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_id',
            field=models.UUIDField(auto_created=True, default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='UUid'),
        ),
    ]
