# Generated by Django 3.1.6 on 2021-10-28 02:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Follower',
            fields=[
                ('author_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='post',
            name='image_content',
        ),
        migrations.RemoveField(
            model_name='post',
            name='items',
        ),
        migrations.RemoveField(
            model_name='post',
            name='post_author',
        ),
        migrations.RemoveField(
            model_name='post',
            name='text_content',
        ),
        migrations.AddField(
            model_name='post',
            name='author',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='author', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='post',
            name='content',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='post',
            name='visibility',
            field=models.CharField(choices=[('PUBLIC', 'Public'), ('PRIVATE', 'Private'), ('FRIENDS', 'Friendonly')], default='PUBLIC', max_length=20),
        ),
        migrations.AlterField(
            model_name='like',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='post',
            name='contentType',
            field=models.CharField(choices=[('text/markdown', 'Markdown'), ('text/plain', 'Plain'), ('application/base64', 'Application'), ('image/png;base64', 'Image Png'), ('image/jpeg;base64', 'Image Jpeg')], default='text/plain', max_length=20),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_type',
            field=models.CharField(default='post', max_length=100, verbose_name='type'),
        ),
    ]
