# Generated by Django 3.1.6 on 2021-12-04 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inbox',
            name='author',
            field=models.CharField(blank=True, default='', max_length=1000, null=True),
        ),
    ]
