# Generated by Django 3.1.6 on 2021-12-03 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServerNodes',
            fields=[
                ('node', models.CharField(max_length=1000, primary_key=True, serialize=False, verbose_name='server_node')),
            ],
        ),
    ]
