# Generated by Django 3.1.6 on 2021-12-04 14:33

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0002_servernodes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='author_id',
            field=models.CharField(auto_created=True, default=uuid.uuid4, max_length=1000, primary_key=True, serialize=False),
        ),
    ]
