# Generated by Django 3.2.8 on 2021-10-27 12:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0002_comment_inbox_like_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='post_type',
            new_name='type',
        ),
        migrations.RemoveField(
            model_name='post',
            name='image_content',
        ),
        migrations.RemoveField(
            model_name='post',
            name='items',
        ),
        migrations.RemoveField(
            model_name='post',
            name='post_author',
        ),
        migrations.RemoveField(
            model_name='post',
            name='text_content',
        ),
        migrations.AddField(
            model_name='author',
            name='myList',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='author',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='author', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='post',
            name='content',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='visibility',
            field=models.CharField(choices=[('PUBLIC', 'Public'), ('PRIVATE', 'Private'), ('FRIENDS', 'Friendonly')], default='PUBLIC', max_length=20),
        ),
        migrations.AlterField(
            model_name='post',
            name='contentType',
            field=models.CharField(choices=[('text/markdown', 'Markdown'), ('text/plain', 'Plain'), ('application/base64', 'Application'), ('image/png;base64', 'Image Png'), ('image/jpeg;base64', 'Image Jpeg')], default='text/plain', max_length=20),
        ),
    ]
