# Generated by Django 3.1.6 on 2021-12-04 23:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0002_auto_20211204_2312'),
        ('authors', '0002_inbox_author'),
    ]

    operations = [
    ]
