# Generated by Django 3.1.6 on 2021-12-06 10:40

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0002_auto_20211205_2220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friendrequest',
            name='author_id',
            field=models.CharField(blank=True, default=uuid.uuid4, max_length=1000, null=True, verbose_name='author_id'),
        ),
        migrations.AlterField(
            model_name='friendrequest',
            name='foreign_author_id',
            field=models.CharField(blank=True, default=uuid.uuid4, max_length=1000, null=True, verbose_name='foreign_author_id'),
        ),
    ]
