# Generated by Django 3.2.8 on 2021-10-17 22:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0002_alter_author_github'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inbox',
            name='inbox_authors',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author', to='authors.author'),
        ),
        migrations.AlterField(
            model_name='inbox',
            name='inbox_contents',
            field=models.CharField(blank=True, default='', max_length=500, null=True, verbose_name='content'),
        ),
    ]
