# Generated by Django 3.1.6 on 2021-12-04 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0003_merge_20211204_2324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='id',
            field=models.CharField(blank=True, default='post', max_length=500, verbose_name='URL_id'),
        ),
        migrations.AlterField(
            model_name='post',
            name='id',
            field=models.CharField(blank=True, default='post', max_length=500, verbose_name='URL_id'),
        ),
    ]
