# Generated by Django 3.1.6 on 2021-11-26 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0003_auto_20211126_1615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_id',
            field=models.UUIDField(editable=False, primary_key=True, serialize=False, verbose_name='id'),
        ),
        migrations.AlterField(
            model_name='post',
            name='type',
            field=models.CharField(default='post', max_length=100, verbose_name='type'),
        ),
    ]
