# Generated by Django 3.2.8 on 2021-10-17 22:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0003_auto_20211017_2231'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inbox',
            name='inbox_authors',
        ),
        migrations.RemoveField(
            model_name='post',
            name='post_author',
        ),
        migrations.AddField(
            model_name='author',
            name='inbox_authors',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='authors', to='authors.inbox'),
        ),
    ]
