# Generated by Django 3.2.8 on 2021-10-27 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0003_auto_20211027_0641'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='myList',
            new_name='followers',
        ),
    ]
