# Generated by Django 3.2.8 on 2021-10-29 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0004_remove_follower_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='follower',
            old_name='id',
            new_name='author_id',
        ),
        migrations.AddField(
            model_name='follower',
            name='author_type',
            field=models.CharField(default='author', max_length=30),
        ),
        migrations.AddField(
            model_name='follower',
            name='displayName',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='follower',
            name='github',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='follower',
            name='host',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='follower',
            name='profileImage',
            field=models.ImageField(blank=True, default='user.jpg', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='follower',
            name='url',
            field=models.CharField(blank=True, default='', max_length=100000, null=True),
        ),
    ]
