# Generated by Django 3.2.7 on 2021-10-18 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0004_auto_20211017_2234'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='inbox_authors',
        ),
        migrations.DeleteModel(
            name='Inbox',
        ),
    ]
