# Generated by Django 3.1.6 on 2021-12-04 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0004_auto_20211204_1435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='author_id',
            field=models.CharField(auto_created=True, default='<function uuid4 at 0x7ff17db0d4c0>', max_length=1000, primary_key=True, serialize=False),
        ),
    ]
