# Generated by Django 3.2.8 on 2021-11-24 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0004_post_post_items'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['published']},
        ),
        migrations.AlterField(
            model_name='post',
            name='published',
            field=models.DateTimeField(auto_now_add=True, verbose_name='published'),
        ),
    ]
