# Generated by Django 3.1.6 on 2021-11-26 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0004_auto_20211126_1655'),
        ('authors', '0003_auto_20211126_1448'),
    ]

    operations = [
    ]
