# Generated by Django 3.1.6 on 2021-12-04 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0005_auto_20211204_2113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='author_id',
            field=models.CharField(default='<function uuid4 at 0x7fb75043c4c0>', max_length=1000, primary_key=True, serialize=False),
        ),
    ]
