# Generated by Django 3.2.7 on 2021-10-18 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0005_auto_20211018_1220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='host',
            field=models.CharField(editable=False, max_length=20),
        ),
        migrations.AlterField(
            model_name='author',
            name='url',
            field=models.URLField(editable=False),
        ),
    ]
