# Generated by Django 3.2.8 on 2021-11-24 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0005_auto_20211124_1311'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('-published',)},
        ),
        migrations.AlterModelTable(
            name='post',
            table='post',
        ),
    ]
