# Generated by Django 3.2.8 on 2021-11-25 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0006_auto_20211124_1319'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inbox',
            fields=[
                ('inbox_type', models.CharField(default='', max_length=100)),
                ('inbox_author_id', models.CharField(default='', max_length=100, primary_key=True, serialize=False)),
                ('items', models.JSONField(null=True)),
            ],
        ),
    ]
