# Generated by Django 3.1.6 on 2021-11-30 11:15

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0007_auto_20211130_0553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_id',
            field=models.UUIDField(auto_created=True, default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='id'),
        ),
        migrations.AlterField(
            model_name='post',
            name='type',
            field=models.CharField(default='post', editable=False, max_length=100, verbose_name='type'),
        ),
    ]
