# Generated by Django 3.1.6 on 2021-11-30 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0008_auto_20211130_1115'),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingAuthor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accept', models.CharField(default='pending', max_length=100)),
                ('pending_author', models.JSONField(blank=True, null=True, verbose_name='pending_author')),
            ],
        ),
    ]
