# Generated by Django 3.1.6 on 2021-12-01 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0008_auto_20211130_0240'),
        ('authors', '0009_pendingauthor'),
    ]

    operations = [
    ]
