# Generated by Django 3.1.6 on 2021-12-01 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0010_merge_20211130_2354'),
    ]

    operations = [
        migrations.RenameField(
            model_name='like',
            old_name='content',
            new_name='context',
        ),
    ]
