# Generated by Django 3.1.6 on 2021-12-01 09:43

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0011_auto_20211130_2356'),
    ]

    operations = [
        migrations.AddField(
            model_name='follower',
            name='realation',
            field=models.UUIDField(auto_created=True, default=uuid.uuid4, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='follower',
            name='author_id',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
