# Generated by Django 3.1.6 on 2021-12-01 09:44

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0012_auto_20211201_0243'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='follower',
            name='realation',
        ),
        migrations.AlterField(
            model_name='follower',
            name='author_id',
            field=models.UUIDField(auto_created=True, default=uuid.uuid4, primary_key=True, serialize=False),
        ),
    ]
